; configuration file

; files
article_file="/home/ermir/Documents/Diploma/csv_processing/finalized-content/test_content.txt"
category_file="/home/ermir/Documents/Diploma/csv_processing/finalized-content/train_content.txt"

; delimiters/separators (should be single-byte), default is 0x1E
article_separator=0x1E
; it was easier to convert a newline from 0x0A than \n, if empty, default is \n
category_list_boundary=0x0A
; default category entry within the category list for an article is ','
category_entry_separator=,
